Fix git_url parameter by escaping % for ConfigParser
The %(project)s placeholder needs to be escaped as %%(project)s in INI files
to prevent Python's ConfigParser from treating it as variable interpolation.
This was causing scheduler and merger pods to crash with:
InterpolationMissingOptionError: option 'git_url' contains an interpolation
key 'project' which is not a valid option name.