Fix nodepool EVS API version for OTC
OTC EVS v3 API does not support the /limits endpoint which causes
nodepool launcher to fail when checking volume quotas. Setting
volume_api_version to '2' forces the use of Cinder v2 API which
is compatible with OTC EVS.

Error: NotFoundException: 404: Client Error for url:
https://evs.eu-de.otc.t-systems.com/v3/\{project_id\}/limits

First occurrence: 2026-01-09 08:05:19 UTC